### ISSUE TITLE
Regarding numpy.matlib error in the code

### ISSUE THREAD

**Issue by Div12345** [aaravindravi/Brain-computer-interfaces#1]
The code throws up an error in the user_dependent_training_mcnn_cnn.ipynb for the numpy.matlib.repmat() call within get_training_data() function.
 
According to [this](https://stackoverflow.com/questions/41818379/why-do-i-have-to-import-this-from-numpy-if-i-am-just-referencing-it-from-the-num/41818451) adding the line 
`import numpy.matlib as npm` and changing it to `npm.repmat()` in the function as well sorted the problem.

So it would be great if you could either add a requirements file with the versions you used to be able to replicate the working without problems or make this change to the notebook.

**Comment by aaravindravi** [comment]
Hi, @Div12345 thank you for reporting this, I will check this and make the updates.

**Comment by aaravindravi** [comment]
Thank you @Div12345 for your feedback, I made the update to the notebook and re-ran the notebook to test the outputs. I have also included a trimmed version of requirements from the latest run of the notebook. Please let me know if this works on your end, also if you face any other issues.
